export { AgentControl } from './agent';
export { View as AgentView } from './agent/view';
export { Home as AgentHome } from './home';
export { PermissionPage } from './permissions';
export { CreateAgentPermission } from './permissions/create/index';
export { EditAgentPermission } from './permissions/edit/index';
export { Products as AgentProduct, AgentProductCreate } from './products';
export { Roles as AgentRoles } from './roles';
export { CreateAgentRole } from './roles/create/index';
export { EditAgentRole } from './roles/edit';
export { Tariff as AgentTariff } from './tariff';
export * from './orders';
export * from './user-permission';
export * from './user-role';
export * from './user-permission';
export * from './user-role';
export * from './tariff';
