export const ROUTES = {
  home: '/',
  global: '/global',
  main: '/dashboard',
  resetEmail: '/email',
  login: '/signin',
  users: '/users',
  create: '/users/create',
  roles: '/roles',
  permissions: '/permissions',
  userRoles: '/user-roles',
  userPermission: '/user-permissions',
  projects: '/project',
  projectsPage: '/projects',
} as const;
