// export { AgentRolesService } from './agent-roles/roles.service';
export { ContractService } from './contract/contract.service';
export { PermissionService } from './permissions/permission.service';
export { RolesService } from './roles/roles.service';
export { TariffService } from './tariff/tarff.service';
export { TariffPermissionService } from './tariffPermission/permission.service';
export { AgentRolesService } from './agent-roles/roles.service';
export { AgentOrderService } from './order';
export { AgentUserRoleService } from './user-role';
export { AgentUserPermissionService } from './user-permission';
export { AgentPermissionsService } from './agent-permissions';
