export { CarPage } from './car';
export * from './car-model';
export { CreateCarPage } from './car/create-page/index';
export { CarType } from './cartype';
export { CreateCarTypePage } from './cartype/create-page';
export { EditCarTypePage } from './cartype/edit-page/index';
export { DriverPage } from './driver';
export { DriverCreatePage } from './driver/create-page';
export { Home as TransferHome } from './home';
export { CreateTariffPage } from './tariff/create-page/index';
export { EditTariffPage } from './tariff/edit-page';
export { Tariff as TransferTariff } from './tariff/index';
